
    "aws": {
        "skillName": "AWS",
        "explanation": "A Cloud Services Platform by Amazon",
        "primaryFamily": "Cloud",
        "secondaryFamily": ["Infrastructure"],
        "synonyms": ["Amazon Web Services"],
        "versions": [],
        "similarTech": ["Azure", "OpenStack", "Google Cloud"],
        "type": "",
        "booleanSynonyms": []
    },
    "amazon web services": {
        "skillName": "AWS",
        "explanation": "A Cloud Services Platform by Amazon",
        "primaryFamily": "Cloud",
        "secondaryFamily": ["Infrastructure"],
        "synonyms": ["Amazon Web Services"],
        "versions": [],
        "similarTech": ["Azure", "OpenStack", "Google Cloud"],
        "type": "",
        "booleanSynonyms": []
    },
    "azure": {
        "skillName": "Azure",
        "explanation": "A Cloud Services Platform by Microsoft",
        "primaryFamily": "Cloud",
        "secondaryFamily": ["Infrastructure"],
        "synonyms": [],
        "versions": [],
        "similarTech": ["AWS", "OpenStack", "Google Cloud"],
        "type": "",
        "booleanSynonyms": []
    },
    "docker": {
        "skillName": "Docker",
        "explanation": "Docker is a computer program that performs operating-system-level virtualization also known as containerization",
        "primaryFamily": "",
        "secondaryFamily": ["Cloud"],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": ["Container", "Containerization", "Kubernetes", "Mesos", "Nomad", "swarm\r"]
    },
    "container": {
        "skillName": "Container",
        "explanation": "",
        "primaryFamily": "Docker",
        "secondaryFamily": [],
        "synonyms": ["Containerization"],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": ["Docker", "Kubernetes", "Mesos", "Nomad", "swarm\r"]
    },
    "containerization": {
        "skillName": "Container",
        "explanation": "",
        "primaryFamily": "Docker",
        "secondaryFamily": [],
        "synonyms": ["Containerization"],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": ["Docker", "Kubernetes", "Mesos", "Nomad", "swarm\r"]
    },
    "kubernetes": {
        "skillName": "Kubernetes",
        "explanation": "container orchestration tool",
        "primaryFamily": "Docker , Container",
        "secondaryFamily": [],
        "synonyms": [],
        "versions": [],
        "similarTech": ["Swarm", "Mesos", "Nomad"],
        "type": "",
        "booleanSynonyms": []
    },
    "swarm": {
        "skillName": "Swarm",
        "explanation": "container orchestration tool",
        "primaryFamily": "Docker -Container",
        "secondaryFamily": [],
        "synonyms": [],
        "versions": [],
        "similarTech": ["Kubernetes", "Mesos", "Nomad"],
        "type": "",
        "booleanSynonyms": []
    },
    "mesos": {
        "skillName": "Mesos",
        "explanation": "container orchestration tool",
        "primaryFamily": "Docker , Container",
        "secondaryFamily": [],
        "synonyms": [],
        "versions": [],
        "similarTech": ["Kubernetes", "Swarm", "Nomad"],
        "type": "",
        "booleanSynonyms": []
    },
    "nomad": {
        "skillName": "Nomad",
        "explanation": "container orchestration tool",
        "primaryFamily": "Docker , Container",
        "secondaryFamily": [],
        "synonyms": [],
        "versions": [],
        "similarTech": ["Kubernetes", "Mesos", "Swarm"],
        "type": "",
        "booleanSynonyms": []
    },
    "paas": {
        "skillName": "PaaS",
        "explanation": "",
        "primaryFamily": "",
        "secondaryFamily": [],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "saas": {
        "skillName": "Saas",
        "explanation": "",
        "primaryFamily": "",
        "secondaryFamily": [],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "baas": {
        "skillName": "BaaS",
        "explanation": "",
        "primaryFamily": "",
        "secondaryFamily": [],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "staas": {
        "skillName": "Staas",
        "explanation": "",
        "primaryFamily": "",
        "secondaryFamily": [],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    }
