
    "hadoop": {
        "skillName": "Hbase",
        "explanation": "HBase is an open-source- non-relational, distributed database modeled after Google's Bigtable and is written in Java",
        "primaryFamily": "BigData",
        "secondaryFamily": ["NoSQL"],
        "synonyms": ["Hadoop"],
        "versions": [],
        "similarTech": [],
        "type": "Cassandra , MongoDB",
        "booleanSynonyms": []
    },
    "pig": {
        "skillName": "Pig",
        "explanation": "Apache Pig is a high-level platform for creating programs that run on Apache Hadoop.",
        "primaryFamily": "BigData",
        "secondaryFamily": ["Hadoop"],
        "synonyms": [],
        "versions": [],
        "similarTech": ["Hive"],
        "type": "",
        "booleanSynonyms": []
    },
    "hive": {
        "skillName": "Hive",
        "explanation": "Apache Hive is a data warehouse software project built on top of Apache Hadoop for providing data summarization, query and analysis.",
        "primaryFamily": "BigData",
        "secondaryFamily": ["Hadoop"],
        "synonyms": [],
        "versions": [],
        "similarTech": ["Pig"],
        "type": "",
        "booleanSynonyms": []
    },
    "hbase": {
        "skillName": "Hbase",
        "explanation": "HBase is an open-source, non,relational, distributed database modeled after Google's Bigtable and is written in Java",
        "primaryFamily": "BigData",
        "secondaryFamily": ["NoSQL"],
        "synonyms": ["Hadoop"],
        "versions": [],
        "similarTech": [],
        "type": "Cassandra$ MongoDB",
        "booleanSynonyms": []
    },
    "spark": {
        "skillName": "Spark",
        "explanation": "Apache Spark is an open,source cluster,computing framework",
        "primaryFamily": "BigData",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": ["MapReduce", "Hive", "Pig"],
        "type": "",
        "booleanSynonyms": []
    },
    "zookeeper": {
        "skillName": "Zookeeper",
        "explanation": "It is essentially a centralized service for distributed systems to a hierarchical key-value store, which is used to provide a distributed configuration service, synchronization service and naming registry for large distributed systems",
        "primaryFamily": "BigData",
        "secondaryFamily": [""],
        "synonyms": ["Zoo Keeper", "Zoo-Keeper"],
        "versions": [],
        "similarTech": ["consul", "eureka", "doozer"],
        "type": "",
        "booleanSynonyms": []
    },
    "zoo keeper": {
        "skillName": "Zookeeper",
        "explanation": "It is essentially a centralized service for distributed systems to a hierarchical key-value store, which is used to provide a distributed configuration service, synchronization service, and naming registry for large distributed systems",
        "primaryFamily": "BigData",
        "secondaryFamily": [""],
        "synonyms": ["Zoo Keeper", "Zoo-Keeper"],
        "versions": [],
        "similarTech": ["consul", "eureka", "doozer"],
        "type": "",
        "booleanSynonyms": []
    },
    "zoo-keeper": {
        "skillName": "Zookeeper",
        "explanation": "It is essentially a centralized service for distributed systems to a hierarchical key-value store, which is used to provide a distributed configuration service, synchronization service, and naming registry for large distributed systems",
        "primaryFamily": "BigData",
        "secondaryFamily": [""],
        "synonyms": ["Zoo Keeper", "Zoo-Keeper"],
        "versions": [],
        "similarTech": ["consul", "eureka", "doozer"],
        "type": "",
        "booleanSynonyms": []
    },
    "sqoop": {
        "skillName": "Sqoop",
        "explanation": "This is a tool that connects Hadoop with various relational databases to transfer data. This can be effectively used to transfer structured data to Hadoop or Hive.",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "oozie": {
        "skillName": "Oozie",
        "explanation": "Apache Oozie is a Java Web application used to schedule Apache Hadoop jobs.",
        "primaryFamily": "Bigdata",
        "secondaryFamily": ["Hadoop"],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "storm": {
        "skillName": "Storm",
        "explanation": "Apache Storm is a distributed real-time computation system, whose applications are designed as directed acyclic graphs",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "jenkins": {
        "skillName": "Jenkins",
        "explanation": "Is used in automating tasks around Continous integration & Deployment",
        "primaryFamily": "",
        "secondaryFamily": ["Devops"],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "mapreduce": {
        "skillName": "MapReduce",
        "explanation": "MapReduce is Hadoop's native batch processing engine.",
        "primaryFamily": "BigData",
        "secondaryFamily": ["Hadoop "],
        "synonyms": ["Map Reduce"],
        "versions": [],
        "similarTech": ["Pig", "Hive", "Spark"],
        "type": "",
        "booleanSynonyms": []
    },
    "map reduce": {
        "skillName": "MapReduce",
        "explanation": "MapReduce is Hadoop's native batch processing engine.",
        "primaryFamily": "BigData",
        "secondaryFamily": ["Hadoop "],
        "synonyms": ["Map Reduce"],
        "versions": [],
        "similarTech": ["Pig", "Hive", "Spark"],
        "type": "",
        "booleanSynonyms": []
    },
    "hdfs": {
        "skillName": "HDFS",
        "explanation": "Hadoop Distributed File System",
        "primaryFamily": "BigData",
        "secondaryFamily": ["Hadoop "],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "cloudera": {
        "skillName": "Cloudera",
        "explanation": "Most popular open source Hadoop-based platform",
        "primaryFamily": "BigData",
        "secondaryFamily": ["Hadoop "],
        "synonyms": ["CDH"],
        "versions": [],
        "similarTech": ["Hortonworks", "MapR"],
        "type": "",
        "booleanSynonyms": []
    },
    "cdh": {
        "skillName": "Cloudera",
        "explanation": "Most popular open source Hadoop-based platform",
        "primaryFamily": "BigData",
        "secondaryFamily": ["Hadoop "],
        "synonyms": ["CDH"],
        "versions": [],
        "similarTech": ["Hortonworks", "MapR"],
        "type": "",
        "booleanSynonyms": []
    },
    "ci": {
        "skillName": "CI",
        "explanation": "Continous Integration in a development environment",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "cd": {
        "skillName": "CD",
        "explanation": "Continous Deployment in a development environment",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "chef": {
        "skillName": "Chef",
        "explanation": "Configuration Management tool",
        "primaryFamily": "Devops",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": ["puppet", "ansible", "salt"],
        "type": "",
        "booleanSynonyms": []
    },
    "puppet": {
        "skillName": "Puppet",
        "explanation": "Configuration Management tool",
        "primaryFamily": "Devops",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": ["chef", "ansible", "salt"],
        "type": "",
        "booleanSynonyms": []
    },
    "salt": {
        "skillName": "Salt",
        "explanation": "Configuration Management tool",
        "primaryFamily": "Devops",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": ["puppet", "ansible", "chef"],
        "type": "",
        "booleanSynonyms": []
    },
    "ansible": {
        "skillName": "Ansible",
        "explanation": "Configuration Management tool",
        "primaryFamily": "Devops",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": ["puppet", "chef", "salt"],
        "type": "",
        "booleanSynonyms": []
    },
    "hortonworks": {
        "skillName": "Hortonworks",
        "explanation": "",
        "primaryFamily": "BigData",
        "secondaryFamily": ["Hadoop "],
        "synonyms": ["HDF", "HDP", "Horton works", "Horton-works"],
        "versions": [],
        "similarTech": ["MapR", "Cloudera"],
        "type": "",
        "booleanSynonyms": []
    },
    "hdf": {
        "skillName": "Hortonworks",
        "explanation": "",
        "primaryFamily": "BigData",
        "secondaryFamily": ["Hadoop "],
        "synonyms": ["HDF", "HDP", "Horton works", "Horton-works"],
        "versions": [],
        "similarTech": ["MapR", "Cloudera"],
        "type": "",
        "booleanSynonyms": []
    },
    "hdp": {
        "skillName": "Hortonworks",
        "explanation": "",
        "primaryFamily": "BigData",
        "secondaryFamily": ["Hadoop "],
        "synonyms": ["HDF", "HDP", "Horton works", "Horton-works"],
        "versions": [],
        "similarTech": ["MapR", "Cloudera"],
        "type": "",
        "booleanSynonyms": []
    },
    "horton works": {
        "skillName": "Hortonworks",
        "explanation": "",
        "primaryFamily": "BigData",
        "secondaryFamily": ["Hadoop "],
        "synonyms": ["HDF", "HDP", "Horton works", "Horton-works"],
        "versions": [],
        "similarTech": ["MapR", "Cloudera"],
        "type": "",
        "booleanSynonyms": []
    },
    "horton-works": {
        "skillName": "Hortonworks",
        "explanation": "",
        "primaryFamily": "BigData",
        "secondaryFamily": ["Hadoop "],
        "synonyms": ["HDF", "HDP", "Horton works", "Horton-works"],
        "versions": [],
        "similarTech": ["MapR", "Cloudera"],
        "type": "",
        "booleanSynonyms": []
    },
    "mapr ": {
        "skillName": "MapR ",
        "explanation": "",
        "primaryFamily": "BigData",
        "secondaryFamily": ["Hadoop "],
        "synonyms": ["Map-R"],
        "versions": [],
        "similarTech": ["Cloudera", "Hortonworks"],
        "type": "",
        "booleanSynonyms": []
    },
    "map-r": {
        "skillName": "MapR ",
        "explanation": "",
        "primaryFamily": "BigData",
        "secondaryFamily": ["Hadoop "],
        "synonyms": ["Map-R"],
        "versions": [],
        "similarTech": ["Cloudera", "Hortonworks"],
        "type": "",
        "booleanSynonyms": []
    },
    "ms hdinsight": {
        "skillName": "MS HDInsight",
        "explanation": "It is a Big Data solution from Microsoft powered by Apache Hadoop which is available as a service in the cloud. HDInsight uses Windows Azure Blob storage as the default file system.",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "presto": {
        "skillName": "Presto",
        "explanation": "Facebook has developed and recently open-sourced its Query engine (SQL-on-Hadoop) named Presto which is built to handle petabytes of data.",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "r": {
        "skillName": "R",
        "explanation": "is a programming language and software environment designed for working with statistics",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "flink": {
        "skillName": "Flink",
        "explanation": "Apache Flink is a streaming dataflow engine, aiming to provide facilities for distributed computation over streams of data.",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "samza": {
        "skillName": "Samza",
        "explanation": "Apache Samza is another distributed stream processing framework. Samza is built on Apache Kafka for messaging and YARN for cluster resource management",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "yarn": {
        "skillName": "Yarn",
        "explanation": "YARN, which stands for Yet Another Resource Negotiator, is the cluster coordinating component of the Hadoop stack.",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "kafka": {
        "skillName": "kafka",
        "explanation": "Apache Kafka is an open-source stream-processing software platform developed by the Apache Software Foundation written in Scala and Java.",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "mahout": {
        "skillName": "Mahout",
        "explanation": "Apache Mahout is a library of scalable machine-learning algorithms, implemented on top of Apache Hadoop and using the MapReduce paradigm.",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "lucene": {
        "skillName": "Lucene",
        "explanation": "",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "solr": {
        "skillName": "Solr",
        "explanation": "",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "avro": {
        "skillName": "Avro",
        "explanation": "Avro provides a convenient way to represent complex data structures within a Hadoop MapReduce job.",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "flume": {
        "skillName": "Flume",
        "explanation": "Flume is a distributed, reliable, and available service for efficiently collecting, aggregating, and moving large amounts of log data.",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "ambari": {
        "skillName": "Ambari",
        "explanation": "The Apache Ambari project is aimed at making Hadoop management simpler by developing software for provisioning, managing, and monitoring Apache Hadoop clusters.",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "impala": {
        "skillName": "Impala",
        "explanation": "Cloudera Impala is the industry’s leading massively parallel processing (MPP) SQL query engine that runs natively in Apache Hadoop.",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "cassandra": {
        "skillName": "Cassandra",
        "explanation": "",
        "primaryFamily": "NoSQL",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "mongodb": {
        "skillName": "MongoDB",
        "explanation": "",
        "primaryFamily": "NoSQL",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "drill": {
        "skillName": "Drill",
        "explanation": "Apache Drill is a schema-free SQL query engine for data exploration.",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "tez": {
        "skillName": "Tez",
        "explanation": "Tez allows Hive and Pig jobs to be written with fewer MapReduce jobs, which makes Hive and Pig scripts run faster.",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "zeppelin": {
        "skillName": "Zeppelin",
        "explanation": "Zeppelin is a Web-based notebook for interactive data analytics. It makes data visualization as easy as drag and drop.",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "nagios": {
        "skillName": "Nagios",
        "explanation": "",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "nginx": {
        "skillName": "Nginx",
        "explanation": "",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "splunk": {
        "skillName": "Splunk",
        "explanation": "",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "docker": {
        "skillName": "Docker",
        "explanation": "",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "git": {
        "skillName": "Git",
        "explanation": "",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "rackspace": {
        "skillName": "Rackspace",
        "explanation": "",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "aws": {
        "skillName": "AWS",
        "explanation": "",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "Cloud",
        "booleanSynonyms": []
    },
    "azure": {
        "skillName": "Azure",
        "explanation": "",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "Cloud",
        "booleanSynonyms": []
    },
    "google cloud": {
        "skillName": "Google Cloud",
        "explanation": "",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "Cloud",
        "booleanSynonyms": []
    },
    "maven": {
        "skillName": "Maven",
        "explanation": "",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "jira": {
        "skillName": "JIRA",
        "explanation": "",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "perl": {
        "skillName": "Perl",
        "explanation": "",
        "primaryFamily": "Scripting",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "shell": {
        "skillName": "Shell",
        "explanation": "",
        "primaryFamily": "Scripting",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "python": {
        "skillName": "Python",
        "explanation": "",
        "primaryFamily": "Scripting",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "bash": {
        "skillName": "Bash",
        "explanation": "",
        "primaryFamily": "Scripting",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "cloudwatch": {
        "skillName": "Cloudwatch",
        "explanation": "",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "scala": {
        "skillName": "Scala",
        "explanation": "",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "golang": {
        "skillName": "GoLang",
        "explanation": "",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "redis": {
        "skillName": "Redis",
        "explanation": "",
        "primaryFamily": "",
        "secondaryFamily": [""],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    }
}