
    "rest": {
        "skillName": "Rest",
        "explanation": "It's a webservice",
        "primaryFamily": "Webservices",
        "secondaryFamily": [],
        "synonyms": ["Restful"],
        "versions": [],
        "similarTech": ["SOAP"],
        "type": "",
        "booleanSynonyms": []
    },
    "restful": {
        "skillName": "Rest",
        "explanation": "It's a webservice",
        "primaryFamily": "Webservices",
        "secondaryFamily": [],
        "synonyms": ["Restful"],
        "versions": [],
        "similarTech": ["SOAP"],
        "type": "",
        "booleanSynonyms": []
    },
    "soap": {
        "skillName": "SOAP",
        "explanation": "It's a webservice",
        "primaryFamily": "Webservices",
        "secondaryFamily": [],
        "synonyms": [],
        "versions": [],
        "similarTech": ["Rest"],
        "type": "",
        "booleanSynonyms": []
    },
    "api": {
        "skillName": "API",
        "explanation": "A Medium to save and retrieve data",
        "primaryFamily": "Webservices",
        "secondaryFamily": [],
        "synonyms": ["APIs"],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "apis": {
        "skillName": "API",
        "explanation": "A Medium to save and retrieve data",
        "primaryFamily": "Webservices",
        "secondaryFamily": [],
        "synonyms": ["APIs"],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "tomcat": {
        "skillName": "Tomcat",
        "explanation": "Java based app server",
        "primaryFamily": "Application Server",
        "secondaryFamily": [],
        "synonyms": [],
        "versions": [],
        "similarTech": ["Weblogic", "Websphere", "Jboss", "Glassfish"],
        "type": "",
        "booleanSynonyms": []
    },
    "weblogic": {
        "skillName": "Weblogic",
        "explanation": "Java based app server",
        "primaryFamily": "Application Server",
        "secondaryFamily": [],
        "synonyms": ["web logic"],
        "versions": [],
        "similarTech": ["Tomcat", "Websphere", "Jboss", "Glassfish"],
        "type": "",
        "booleanSynonyms": []
    },
    "web logic": {
        "skillName": "Weblogic",
        "explanation": "Java based app server",
        "primaryFamily": "Application Server",
        "secondaryFamily": [],
        "synonyms": ["web logic"],
        "versions": [],
        "similarTech": ["Tomcat", "Websphere", "Jboss", "Glassfish"],
        "type": "",
        "booleanSynonyms": []
    },
    "websphere ": {
        "skillName": "Websphere ",
        "explanation": "It is a software framework and middleware that hosts Java based web application",
        "primaryFamily": "Application Server",
        "secondaryFamily": [],
        "synonyms": ["Web sphere"],
        "versions": [],
        "similarTech": ["Weblogic", "Tomcat", "Jboss", "Glassfish"],
        "type": "",
        "booleanSynonyms": []
    },
    "web sphere": {
        "skillName": "Websphere ",
        "explanation": "It is a software framework and middleware that hosts Java based web application",
        "primaryFamily": "Application Server",
        "secondaryFamily": [],
        "synonyms": ["Web sphere"],
        "versions": [],
        "similarTech": ["Weblogic", "Tomcat", "Jboss", "Glassfish"],
        "type": "",
        "booleanSynonyms": []
    },
    "jboss": {
        "skillName": "JBOSS",
        "explanation": "App server provided by RedHat",
        "primaryFamily": "Application Server",
        "secondaryFamily": [],
        "synonyms": [],
        "versions": [],
        "similarTech": ["Weblogic", "Websphere", "Tomcat", "Glassfish"],
        "type": "",
        "booleanSynonyms": []
    },
    "glassfish": {
        "skillName": "GlassFish",
        "explanation": "",
        "primaryFamily": "Application Server",
        "secondaryFamily": [],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "git": {
        "skillName": "GIT",
        "explanation": "Version Controlling tool",
        "primaryFamily": "",
        "secondaryFamily": [],
        "synonyms": [],
        "versions": [],
        "similarTech": ["SVN"],
        "type": "",
        "booleanSynonyms": []
    },
    "svn": {
        "skillName": "SVN",
        "explanation": "Version Controlling tool",
        "primaryFamily": "",
        "secondaryFamily": [],
        "synonyms": [],
        "versions": [],
        "similarTech": ["GIT"],
        "type": "",
        "booleanSynonyms": []
    },
    "eclipse": {
        "skillName": "Eclipse",
        "explanation": "An IDE mostly used in Java",
        "primaryFamily": "IDE",
        "secondaryFamily": [],
        "synonyms": [],
        "versions": [],
        "similarTech": ["Netbeans", "Intellij", "visual studio"],
        "type": "",
        "booleanSynonyms": []
    },
    "netbeans": {
        "skillName": "NetBeans",
        "explanation": "An IDE mostly used in Java",
        "primaryFamily": "IDE",
        "secondaryFamily": [],
        "synonyms": ["Net Beans"],
        "versions": [],
        "similarTech": ["Eclipse", "Intellij", "visual studio"],
        "type": "",
        "booleanSynonyms": []
    },
    "net beans": {
        "skillName": "NetBeans",
        "explanation": "An IDE mostly used in Java",
        "primaryFamily": "IDE",
        "secondaryFamily": [],
        "synonyms": ["Net Beans"],
        "versions": [],
        "similarTech": ["Eclipse", "Intellij", "visual studio"],
        "type": "",
        "booleanSynonyms": []
    },
    "intellij": {
        "skillName": "IntelliJ",
        "explanation": "An IDE mostly used in Java",
        "primaryFamily": "IDE",
        "secondaryFamily": [],
        "synonyms": [],
        "versions": [],
        "similarTech": ["Netbeans", "Intellij", "eclipse"],
        "type": "",
        "booleanSynonyms": []
    },
    "visual studio": {
        "skillName": "Visual Studio",
        "explanation": "AN IDE from Microsoft",
        "primaryFamily": "IDE",
        "secondaryFamily": [],
        "synonyms": [],
        "versions": [],
        "similarTech": ["Netbeans", "Intellij", "eclipse"],
        "type": "",
        "booleanSynonyms": []
    },
    "ant": {
        "skillName": "ANT",
        "explanation": "",
        "primaryFamily": "",
        "secondaryFamily": [],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "maven": {
        "skillName": "Maven",
        "explanation": "",
        "primaryFamily": "",
        "secondaryFamily": [],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    },
    "gradle": {
        "skillName": "Gradle",
        "explanation": "",
        "primaryFamily": "",
        "secondaryFamily": [],
        "synonyms": [],
        "versions": [],
        "similarTech": [],
        "type": "",
        "booleanSynonyms": []
    }
}