const URL={
    HOME_ORIGIN:"https://api.fellowapp.co/api/v1"
}
URL.GET_CANDIDATE_JOB_RECRUITER_OBJ=URL.HOME_ORIGIN+"getInitialDetails.php";
URL.SUBMIT_CANDIDATE_CHAT_RESPONSE=URL.HOME_ORIGIN+"/chatbot";
// URL.SUBMIT_CANDIDATE_CHAT_RESPONSE=URL.HOME_ORIGIN+"addCandidateResponse.php";
URL.GET_CLIENT_OBJ=URL.HOME_ORIGIN+"getClientObj.php";
URL.FEEBACK_TO_RECRUITER=URL.HOME_ORIGIN+"feedbackByCandidate.php";
URL.ADD_ONE_ON_ONE_CHAT=URL.HOME_ORIGIN+"addOneOnOneChat.php";
URL.VERIFY_TOKEN = URL.HOME_ORIGIN+"verifyToken.php";
URL.ADD_BOT_CHAT=URL.HOME_ORIGIN+"addBotChat.php";
URL.ADD_FCM_TOKEN=URL.HOME_ORIGIN+"addBotChat.php";

URL.GET_BOT_CHATS=URL.HOME_ORIGIN+"/chatbot";
URL.GET_JOBS=URL.HOME_ORIGIN+"/jobs-candidate";
URL.GET_CAND=URL.HOME_ORIGIN+"/candidate";
URL.GET_QUEST_ID=URL.HOME_ORIGIN+"/jobs-questions";
URL.GET_JOB_CAND_ID=URL.HOME_ORIGIN+"/jobs-candidate";
export default URL;